version: "3.9"
services:
  web:
    build: .
    ports:
      - 8000:8000
    env-file: .env
  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:            
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
  rdis:
    image: redis:alpine
    expose: 
      - 6379
    command: redis-server
    volumes: 
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  mysql:
    image: mysql:5.7
    volumes: 
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kimchinese
volumes:
  mysql-data:
  redis-data:
  redis-conf:
  caddy_data:
  caddy_config:
