[[redirects]]
from = "/"
to = "/.netlify/functions/onrequest"
status = 200
force = true
_generated_by_eleventy_serverless = "onrequest"

[functions]
directory = "netlify/functions/"
node_bundler = "esbuild"

[dev]
envFiles = [ ".dev.env" ]
