const { DateTime } = require("luxon")

const nextDay = DateTime.utc()
  .setZone("Asia/Seoul")
  .plus({ days: 1 })
  .startOf("day")
  .toUTC()
  .toISO()
console.log(DateTime.utc().toISO())
console.log(DateTime.utc().setZone("Asia/Seoul").toISO())
console.log(
  DateTime.utc().setZone("Asia/Seoul").plus({ days: 1 }).startOf("day").toISO()
)
console.log(
  DateTime.utc()
    .setZone("Asia/Seoul")
    .plus({ days: 1 })
    .startOf("day")
    .toUTC()
    .toISO()
)
console.log(nextDay)
console.log(DateTime.local({ zone: "Asia/Seoul" }).toISO())
console.log(DateTime.utc().toISO())
